
export type Defence =
    | "ikkyo"
    | "nikyo"
    | "sankyo"
    | "yonkyo"
    | "gokyo"
    | "irimi nage"
    | "kokyu nage"
    | "shiho nage"
    | "ude kime nage"
    | "ude garami"
    | "sokumen irimi nage"
    | "uchi kaiten nage"
    | "soto kaiten nage"
    | "tenchi nage"
    | "koshi nage"
    | "kote gaeshi"
    | "kokyu ho"
    | "sumi otoshi"
    | "aiki otoshi"
    | "juji garami"
    | "hiji kimo osae"
    | "uchi kaiten sankyo";
